#define a persistent volume claim for mysql storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim #name of the storage
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    -ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#configure  deployment of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  mane: mysql
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: idsa
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
#defining a service to expose mysql to other service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None

